// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnVsN-Jm-VupYbAjy2CXKky7hTUdv4rMY',
    appId: '1:869356654978:web:dbe8b4cebb0eaaf6483f9b',
    messagingSenderId: '869356654978',
    projectId: 'iot-test-17943',
    authDomain: 'iot-test-17943.firebaseapp.com',
    storageBucket: 'iot-test-17943.appspot.com',
    measurementId: 'G-KTRVQEE0FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjny54UhE52RFmrLvAsdIoOopF2E2bP9o',
    appId: '1:869356654978:android:0869cde529cef7e2483f9b',
    messagingSenderId: '869356654978',
    projectId: 'iot-test-17943',
    storageBucket: 'iot-test-17943.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHTzSaKHUrqerl5fwqb4wqNX0NxEpJ750',
    appId: '1:869356654978:ios:7f0dfcde136c1b0c483f9b',
    messagingSenderId: '869356654978',
    projectId: 'iot-test-17943',
    storageBucket: 'iot-test-17943.appspot.com',
    iosBundleId: 'com.example.iotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHTzSaKHUrqerl5fwqb4wqNX0NxEpJ750',
    appId: '1:869356654978:ios:7f0dfcde136c1b0c483f9b',
    messagingSenderId: '869356654978',
    projectId: 'iot-test-17943',
    storageBucket: 'iot-test-17943.appspot.com',
    iosBundleId: 'com.example.iotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnVsN-Jm-VupYbAjy2CXKky7hTUdv4rMY',
    appId: '1:869356654978:web:aa2421fb6c528839483f9b',
    messagingSenderId: '869356654978',
    projectId: 'iot-test-17943',
    authDomain: 'iot-test-17943.firebaseapp.com',
    storageBucket: 'iot-test-17943.appspot.com',
    measurementId: 'G-1HLL22CK2N',
  );
}
